# AI - Natural Language Processing

### The problem?

- Endless amounts of unstructured data found in emails, tweets, letters, memos, etc.
- Even in transcripts
- How can we make sense of all this data?
- How can we 'easily' find relevant information for our reporting?

### The solution?
- Artificial Intelligence to process all that text using **natural language processing**!
- <a href="https://machinelearningmastery.com/natural-language-processing/">Learn more</a> about the complexity and the history of NLP.
- The use of ```large language models```!

### Journalism examples

- <a href="http://doctors.ajc.com/part_1_license_to_betray/">License to betray</a> – Finding word stems and roots to uncover abuse. (<a href="http://doctors.ajc.com/about_this_investigation/?ecmp=doctorssexabuse_microsite_stories">More info</a>)
- <a href="https://www.revealnews.org/article/federal-judges-rulings-favored-companies-in-which-he-owned-stock/">Federal judge’s rulings favored companies in which he owned stock</a> – Finding all stock owned by judges in disclosure forms and comparing to caseloads.
- <a href="https://www.latimes.com/local/cityhall/la-me-crime-stats-20151015-story.html">LAPD underreported serious assaults, skewing crime stats for 8 years</a> – Text classification analysis.

### The tools

- Spacy v. NLTK
- NLTK launched in 2001, Spacy in 2015
- NLTK is now bloated and complex, requiring many steps to deal with many changes etc.
- Spacy is lean and modern, and can compute some text 4x to 20x faster than NLTK.
- Spacy does **nearly** everything that NLTK does, but better.
- NLTK, however, is still the library of choice for sentiment analysis.

However, sentiment analysis in journalism can be problematic. Be extra wary of NLP's use for news analysis. AI can easily misinterpret the sentiment in this sentence:

"It is a great movie if you have the taste and sensibilities of a five-year-old boy."

It's best to stick to the following types of analysis:

- Mentions of a word or concept (who said something...when and how many times?)
- Frequency of target terms or topics (how often were keywords used in speeches, transcripts, etc)
- Words over time (a timeline that shows frequency of words over time)
- Missing words (really a flip of words over time to show how people stopped using certain concepts or terms)
- Key people, places, companies (identify proper nouns and places for reporting)
- Comparisons (for example financial disclosures over time...which stocks were added or removed over the years)

# Working with Spacy

## Step 1. Install Spacy

If this first time ever using spacy on this computer, you must first do either the ```!conda install``` or ```!pip install```:

In [ ]:
pip install -U spacy

#### Which language model is best for you?
<a href="https://spacy.io/usage/models">https://spacy.io/usage/models</a>

## Step 2. Install language model

### ## import that language model

In [ ]:
!python -m spacy download en_core_web_sm

In [1]:
## import libary.
import pandas as pd
import glob
import spacy

### Place English libary into a ```nlp``` pipeline

In [ ]:
## build nlp pipeline (a function will tokenize, parse and ner for us)
nlp = spacy.load("en_core_web_sm")

In [ ]:
## what type of object is nlp - it's a pipeline that's going to tokenize the thing. 
type(nlp)

## Step 3. Text analysis

In [13]:
### Sample English text: looks like it works without the u as well.
text = u'''\
On May 10, 2011, Microsoft announced its acquisition of Skype Technologies, \
creator of the VoIP service Skype, for $8.5 billion. \
Microsoft is headquartered near Seattle Washington while Skype remains in Palo Alto, California. \
Sandeep Junnarkar got this from Wikipedia. \
But he'd rather head to Paris, France to see the Mona Lisa at the Louvre. \
The Hudson River should really be called by its original native name, Mahicantuck, which means "the river that flows two ways." \
Mahicantuck flows for 315 miles to the Atlantic Ocean from its source at Mt. Mercy, the tallest peak in New York state.
'''

In [15]:
## CALL the text
text

'On May 10, 2011, Microsoft announced its acquisition of\xa0Skype Technologies, creator of the\xa0VoIP\xa0service\xa0Skype, for $8.5 billion. Microsoft is headquartered near Seattle Washington while Skype remains in Palo Alto, California. Sandeep Junnarkar got this from Wikipedia. But he\'d rather head to Paris, France to see the Mona Lisa at the Louvre. The Hudson River should really be called by its original native name, Mahicantuck, which means "the river that flows two ways." Mahicantuck flows for 315 miles to the Atlantic Ocean from its source at Mt. Mercy, the tallest peak in New York state.\n'

In [17]:
## PRINT the tex
print(text)

On May 10, 2011, Microsoft announced its acquisition of Skype Technologies, creator of the VoIP service Skype, for $8.5 billion. Microsoft is headquartered near Seattle Washington while Skype remains in Palo Alto, California. Sandeep Junnarkar got this from Wikipedia. But he'd rather head to Paris, France to see the Mona Lisa at the Louvre. The Hudson River should really be called by its original native name, Mahicantuck, which means "the river that flows two ways." Mahicantuck flows for 315 miles to the Atlantic Ocean from its source at Mt. Mercy, the tallest peak in New York state.

### Tokenize our text

- Tokenizing is always the first step in text analysis. 
- It breaks all text into isolated but related units (including spaces, symbols, punctuation, numbers, words etc.)
- However, it retains the connection between all the words, sentences, and paragraphs.

In [19]:
## let's run the nlp function and create a spacy doc- just like how we call beatiful soup objects soup, we call tokenized objects doc.
doc = nlp(text)

In [21]:
## CALL doc
doc

On May 10, 2011, Microsoft announced its acquisition of Skype Technologies, creator of the VoIP service Skype, for $8.5 billion. Microsoft is headquartered near Seattle Washington while Skype remains in Palo Alto, California. Sandeep Junnarkar got this from Wikipedia. But he'd rather head to Paris, France to see the Mona Lisa at the Louvre. The Hudson River should really be called by its original native name, Mahicantuck, which means "the river that flows two ways." Mahicantuck flows for 315 miles to the Atlantic Ocean from its source at Mt. Mercy, the tallest peak in New York state.

In [ ]:
## what type of data is it?
type(doc)

In [ ]:
## show each token- groups separated by a space, or punctuations (in which case, the punctuation is also a token).
for item in doc:
    print(item)
    print("****")

### Parts of speech

In [ ]:
## print all parts of speech words. pos-parts of speech (numeric value), pos_ (what kind in english)
for token in doc:
    print(f"{token.text}--->{token.pos}--->{token.pos_}")

### Step 4. Named Entity Recognition (NER)

#### Spacy easily returns the words that matter to us like names of companies, people, places, art works, numbers, etc.

- ```.ents``` ------------> Finds all entities in doc spacy object.

- ```ent.text``` ------------> The actual text.

- ```ent.label``` ------------> A numeric code for the entity.

- ```ent.label_``` ------------> The word's entity category.

- ```spacy.explain(ent.label_)``` ---------> A description of the category.

In [23]:
### call doc
doc

On May 10, 2011, Microsoft announced its acquisition of Skype Technologies, creator of the VoIP service Skype, for $8.5 billion. Microsoft is headquartered near Seattle Washington while Skype remains in Palo Alto, California. Sandeep Junnarkar got this from Wikipedia. But he'd rather head to Paris, France to see the Mona Lisa at the Louvre. The Hudson River should really be called by its original native name, Mahicantuck, which means "the river that flows two ways." Mahicantuck flows for 315 miles to the Atlantic Ocean from its source at Mt. Mercy, the tallest peak in New York state.

In [25]:
## find all entities
for word in doc.ents:
    print(word)

May 10, 2011
Microsoft
Skype Technologies
Skype
$8.5 billion
Microsoft
Seattle Washington
Skype
Palo Alto
California
Sandeep Junnarkar
Wikipedia
Paris, France
the Mona Lisa
Louvre
The Hudson River
Mahicantuck
Mahicantuck
315 miles
the Atlantic Ocean
Mt. Mercy
New York

In [27]:
## find all entities with their label. 

for word in doc.ents:
    print(f"{word}--->{word.label_}")

May 10, 2011--->DATE
Microsoft--->ORG
Skype Technologies--->ORG
Skype--->ORG
$8.5 billion--->MONEY
Microsoft--->ORG
Seattle Washington--->GPE
Skype--->ORG
Palo Alto--->GPE
California--->GPE
Sandeep Junnarkar--->PERSON
Wikipedia--->ORG
Paris, France--->GPE
the Mona Lisa--->WORK_OF_ART
Louvre--->FAC
The Hudson River--->LOC
Mahicantuck--->LOC
Mahicantuck--->LOC
315 miles--->QUANTITY
the Atlantic Ocean--->LOC
Mt. Mercy--->LOC
New York--->GPE

In [29]:
## find all entities with their label and label descriptors
for word in doc.ents:
    print(f"{word}--->{word.label_}--->{spacy.explain(word.label_)}")

May 10, 2011--->DATE--->Absolute or relative dates or periods
Microsoft--->ORG--->Companies, agencies, institutions, etc.
Skype Technologies--->ORG--->Companies, agencies, institutions, etc.
Skype--->ORG--->Companies, agencies, institutions, etc.
$8.5 billion--->MONEY--->Monetary values, including unit
Microsoft--->ORG--->Companies, agencies, institutions, etc.
Seattle Washington--->GPE--->Countries, cities, states
Skype--->ORG--->Companies, agencies, institutions, etc.
Palo Alto--->GPE--->Countries, cities, states
California--->GPE--->Countries, cities, states
Sandeep Junnarkar--->PERSON--->People, including fictional
Wikipedia--->ORG--->Companies, agencies, institutions, etc.
Paris, France--->GPE--->Countries, cities, states
the Mona Lisa--->WORK_OF_ART--->Titles of books, songs, etc.
Louvre--->FAC--->Buildings, airports, highways, bridges, etc.
The Hudson River--->LOC--->Non-GPE locations, mountain ranges, bodies of water
Mahicantuck--->LOC--->Non-GPE locations, mountain ranges, bodies of water
Mahicantuck--->LOC--->Non-GPE locations, mountain ranges, bodies of water
315 miles--->QUANTITY--->Measurements, as of weight or distance
the Atlantic Ocean--->LOC--->Non-GPE locations, mountain ranges, bodies of water
Mt. Mercy--->LOC--->Non-GPE locations, mountain ranges, bodies of water
New York--->GPE--->Countries, cities, states

## Import hearings
Download <a href="https://drive.google.com/file/d/1EUYLeHpHAAW2MGsrT6_jov9cJ-IuDLg-/view?usp=sharing">this senate hearing</a> and turn it into a spacy doc.

In [ ]:
## download larger, more accurate model.

In [3]:
! python -m spacy download en_core_web_trf

Collecting en-core-web-trf==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.8.0/en_core_web_trf-3.8.0-py3-none-any.whl (457.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 457.4/457.4 MB 19.7 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: spacy-curated-transformers<1.0.0,>=0.2.2 in /opt/anaconda3/lib/python3.12/site-packages (from en-core-web-trf==3.8.0) (0.3.1)
Requirement already satisfied: curated-transformers<0.2.0,>=0.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (0.1.1)
Requirement already satisfied: curated-tokenizers<0.1.0,>=0.0.9 in /opt/anaconda3/lib/python3.12/site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (0.0.9)
Requirement already satisfied: torch>=1.12.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.9.0)
Requirement already satisfied: regex>=2022 in /opt/anaconda3/lib/python3.12/site-packages (from curated-tokenizers<0.1.0,>=0.0.9->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2024.9.11)
Requirement already satisfied: filelock in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (4.15.0)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (75.1.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.3)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2024.6.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.1.3)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')

In [5]:
import en_core_web_trf

In [31]:
## create our pipeline
nlp = en_core_web_trf.load()

In [36]:
## pull hearing into notebook
hearing = glob.glob("*hearing*")
hearing

['senate-hearing.txt']

In [38]:
## read into a variable
with open(hearing[0], "r") as text:
    print(type(text))

<class '_io.TextIOWrapper'>

In [44]:
with open(hearing[0], "r") as text:
    # print(text)
    all_text = text.read()

all_text

"[Senate Hearing 118-22]\n[From the U.S. Government Publishing Office]\n\n\n                                                        S. Hrg. 118-22\n\n                   IMPLEMENTING IIJA: PERSPECTIVES ON\n          THE DRINKING WATER AND WASTEWATER INFRASTRUCTURE ACT\n\n=======================================================================\n\n                                HEARING\n\n                               BEFORE THE\n\n                              COMMITTEE ON\n                      ENVIRONMENT AND PUBLIC WORKS\n\n                          UNITED STATES SENATE\n\n                    ONE HUNDRED EIGHTEENTH CONGRESS\n\n                             FIRST SESSION\n\n                               __________\n\n                             MARCH 15, 2023\n\n                               __________\n\n  Printed for the use of the Committee on Environment and Public Works\n  \n[GRAPHIC NOT AVAILABLE IN TIFF FORMAT]  \n\n\n        Available via the World Wide Web: http://www.govinfo.gov\n        \n                               __________\n\n                                \n                    U.S. GOVERNMENT PUBLISHING OFFICE                    \n52-512 PDF                  WASHINGTON : 2023                    \n          \n-----------------------------------------------------------------------------------      \n        \n        \n        \n               COMMITTEE ON ENVIRONMENT AND PUBLIC WORKS\n\n                    ONE HUNDRED EIGHTEENTH CONGRESS\n\n                             FIRST SESSION\n\n                  THOMAS R. CARPER, Delaware, Chairman\n          SHELLEY MOORE CAPITO, West Virginia, Ranking Member\n\nBENJAMIN L. CARDIN, Maryland         KEVIN CRAMER, North Dakota\nBERNARD SANDERS, Vermont             CYNTHIA M. LUMMIS, Wyoming\nSHELDON WHITEHOUSE, Rhode Island     MARKWAYNE MULLIN, Oklahoma\nJEFF MERKLEY, Oregon                 PETE RICKETTS, Nebraska\nEDWARD J. MARKEY, Massachusetts      JOHN BOOZMAN, Arkansas\nDEBBIE STABENOW, Michigan            ROGER WICKER, Mississippi\nMARK KELLY, Arizona                  DAN SULLIVAN, Alaska\nALEX PADILLA, California             LINDSEY O. GRAHAM, South Carolina\nJOHN FETTERMAN, Pennsylvania\n\n               Courtney Taylor, Democratic Staff Director\n               Adam Tomlinson, Republican Staff Director\n                            \n                            \n                            C O N T E N T S\n\n                              ----------                              \n                                                                   Page\n\n                             MARCH 15, 2023\n                           OPENING STATEMENTS\n\nCarper, Hon. Thomas R., U.S. Senator from the State of Delaware..     1\nCapito, Hon. Shelley Moore, U.S. Senator from the State of West \n  Virginia.......................................................     3\n\n                               WITNESSES\n\nFox, Hon. Radhika, Assistant Administrator, Office of Water, \n  Environmental Protection Agency................................     6\n    Prepared statement...........................................     9\n    Responses to additional questions from Senator Carper........    18\n    Response to an additional question from Senator Fetterman....    23\n    Responses to additional questions from Senator Capito........    25\n    Response to an additional question from:\n        Senator Cramer...........................................    28\n        Senator Lummis...........................................    30\n    Responses to additional questions from:\n        Senator Mullin...........................................    30\n        Senator Sullivan.........................................    32\nHayman, Randy E., Commissioner and CEO, Philadelphia Water \n  Department.....................................................    70\n    Prepared statement...........................................    73\n    Responses to additional questions from Senator Carper........    82\nSigmund, Thomas W., President, National Association of Clean \n  Water Agencies, Executive Director, NEW Water..................    90\n    Prepared statement...........................................    93\n    Responses to additional questions from Senator Carper........   161\nEmery, Katheryn D., Director, Division of Water and Waste \n  Management, West Virginia Department of Environmental \n  Protection.....................................................   166\n    Prepared statement...........................................   168\n    Responses to additional questions from Senator Carper........   175\n\n                          ADDITIONAL MATERIAL\n\nLetter to Senator Charles Schumer et al. from the American \n  Sustainable Business Network, March 6, 2023....................    45\nLetter to Senators Carper and Capito from the California \n  Association of Sanitation Agencies, March 15, 2023.............   188\nLetter to Senators Carper and Capito from American Rivers, March \n  14, 2023.......................................................   192\nTestimony of the Council of Infrastructure Financing Authorities, \n  March 15, 2023.................................................   220\n\n \n IMPLEMENTING IIJA: PERSPECTIVES ON THE DRINKING WATER AND WASTEWATER \n                           INFRASTRUCTURE ACT\n\n                              ----------                              \n\n\n                       WEDNESDAY, MARCH 15, 2023\n\n                                       U.S. Senate,\n                 Committee on Environment and Public Works,\n                                                    Washington, DC.\n    The Committee met, pursuant to notice, at 10:05 a.m. in \nroom 406, Dirksen Senate Office Building, Hon. Thomas R. Carper \n(Chairman of the Committee) presiding.\n    Present: Senators Carper, Capito, Cardin, Markey, Kelly, \nCramer, Lummis, Sullivan, and Ricketts.\n\n          OPENING STATEMENT OF HON. THOMAS R. CARPER, \n            U.S. SENATOR FROM THE STATE OF DELAWARE\n\n    Senator Carper. Good morning. Let me call this hearing to \norder.\n    We are here today to examine the implementation of the \nDrinking Water and Wastewater portions of the Bipartisan \nInfrastructure Law. As you will recall, this historic \nbipartisan law is helping to deliver clean drinking water to \nmillions of households and schools across our country.\n    Before we do that, let me start by saying how grateful I am \nto both panels of witnesses that are joining us today, \nincluding representatives of drinking water, clean water, as \nwell as small and large utilities. We are particularly \nappreciative that Assistant Administrator Radhika Fox, who \nleads EPA's Office of Water, has joined us.\n    Welcome.\n    To all of our guests; we have a lot of folks, Senator \nCapito, I don't think we have had that many photos before a \nhearing in a long time. We want to remember this day.\n    Yesterday, the Biden administration took a major step in \naddressing the presence of toxic forever chemicals known as \nPFAS in our drinking water. This announcement was some 20 years \nin the making. It is an issue that is very important to, as it \nturns out, to West Virginia and to Delaware, and frankly, to \nall the other 48 States across the country. I want to commend \nthe President; I want to commend Administrator Regan, Assistant \nAdministrator Fox, and all of EPA for proposing a thoughtful, \nscience based, national drinking water standard for PFAS.\n    This critical step to protecting our drinking water comes \non top of the President calling for significant investments to \nprotect our public health and environment in his proposed 2024 \nbudget released last week. In his budget, the President \nrequested more than $12 billion for EPA, $1.9 billion, a 19 \npercent increase from the 2023 enacted level. More than $4 \nbillion of that proposal is reserved for water infrastructure. \nThat includes an additional $219 million for grants to reduce \nthe amount of lead in drinking water, to test for and remove \nlead in schools, and to replace lead pipes.\n    This budget builds on the Committee's work in the \nBipartisan Infrastructure Law to invest in our nation's water \ninfrastructure, which brings us to the topic of today's \nhearing: Oversight of the implementation of the drinking water \nand wastewater portions of the Bipartisan Infrastructure Law.\n    As we have discussed, Democrats and Republicans on this \npanel, it is not just enough to enact landmark legislation like \nthis, but it is important that it be appropriately implemented \nand that we exercise our responsibilities with respect to \noversight. That is part of what we are doing here today.\n    Our work on this Committee to improve our water \ninfrastructure is personal to me. We have some folks here from \nWest Virginia who have joined us; welcome.\n    If you're from West Virginia, raise your hand. If you would \nlike to be from West Virginia, raise your hand.\n    [Laughter.]\n    Senator Carper. Almost everybody, for the record.\n    Our work in this Committee is to improve our water and \ninfrastructure. As I said, it is personal to me, rooted in my \nfaith and my family's history in Raleigh County, West Virginia. \nSome of you may recall that Matthew 25 calls on all of us to \nactually care for those that are in need, the least of these, \nto give those that are thirsty something to drink. For me, this \nincludes that ensuring that Americans have access to clean, \nsafe, and reliable water services.\n    Some of you may recall, I was born in Beckley, in a coal \nmining town in the southern part of the State. For 2 of those 6 \nyears that we actually lived there, my first 6 years of my \nlife, we lived alongside a stream. Our Ranking Member has heard \nof Beaver; she's been to Beaver right outside of Beckley many \ntimes. There is a creek that goes through there called Beaver \nCreek. My sister and I lived alongside Beaver Creek.\n    We would play along the banks of that creek. We would try \nto catch small fish, sometimes frogs, and we were never allowed \nto eat any of them. Nor were we allowed to drink the water from \nBeaver Creek. That is because many of the nearby septic tanks \nwere not well maintained, and as a result raw sewage and other \npollution could seep into that creek. At the time, our \nsituation was not too different from that of many other small \ncommunities in West Virginia and across the country.\n    In the years that followed, our Government has responded to \nthis water crisis by creating grant and later loan programs \nthat made it easier for communities across our country to build \nand upgrade drinking water and wastewater treatment systems. \nOver time, these programs languished and were in dire need of \nupdating.\n    That is why I, along with our Ranking Member, Senator \nCapito, Senator Cardin, Senator Lummis, Senator Duckworth, \nSenator Cramer, and many other members of this Committee and \noff this Committee joined forces to address this need. We \nworked in an overwhelmingly bipartisan way to draft the \nDrinking Water and Wastewater Infrastructure Act. You will \nrecall that our legislation included historic investments in \nEPA's State Revolving Funds. Those funds were the primary \nvehicle for State and local governments to finance water \ninfrastructure projects throughout America.\n    We advanced our legislation out of Committee unanimously \nand later passed it out of the full Senate by a vote of 89 to \n2. If the American people are looking for bipartisanship, they \nneed look no further than this Committee and its work on \ninfrastructure. This water bill, combined with our Committee's \nhistoric highway legislation, roads, highways, bridges, served \nas the foundation of the Bipartisan Infrastructure Law, which \nPresident Biden signed into law in November 2021, a happy day \nfor all of us.\n    The Bipartisan Infrastructure Law invested an unprecedented \n$55 billion, $55 billion, that's billion with a B, to improve \ndrinking water and wastewater systems in communities across our \ncountry, and it was paid for, fully offset. This remains the \nsingle largest water infrastructure investment in our nation's \nhistory. Let me repeat that: This remains the single largest \nwater infrastructure investment in our nation's history. Now, \nEPA has the responsibility of putting these dollars, these \ninvestments, to work for all of the American people.\n    Today's hearing is an opportunity to gain a deeper \nunderstanding of how this process is going. This hearing will \nallow us to explore future opportunities to improve the way we \ninvest in our drinking water and wastewater infrastructure. \nThat includes investigating how the Bipartisan Infrastructure \nLaw programs are benefiting communities with the greatest need \nand what additional authorities or changes might be needed to \nmake the program function better.\n    I like to say, everything I do, I know I can do better. And \nas proud as we are of this legislation, we know that we can \nstill improve on it further. For example, is there more that \ncould be done to adapt these programs to changes in our climate \nand our population and the age of our infrastructure?\n    As I said earlier, we look forward to hearing from our \ndistinguished panels of witnesses today. Before we do, let me \nturn to Senator Capito for her opening remarks.\n    Senator Capito, you are recognized.\n\n        OPENING STATEMENT OF HON. SHELLEY MOORE CAPITO, \n          U.S. SENATOR FROM THE STATE OF WEST VIRGINIA\n\n    Senator Capito. Thank you, Mr. Chairman, and thank all of \nyou for being here today.\n    I would like to thank Assistant Administrator Fox for not \njust being here today but for the lines of communication that \nyou have kept open, as you promised in your hearing when you \ncame before this Committee. You have stayed true to your word. \nI certainly appreciate that, from my perspective.\n    I would also like to thank you for finally, after many \nyears of me banging the gavel and the gong and also with the \nChair to set that safe drinking level for PFAS. That is going \nto have many impacts across the country. Certainly, safe, \nclean, and healthy water is at the top of the list for all of \nus.\n    This Committee values your perspectives on the challenges, \nand other witnesses' as well, facing this nation's water \ninfrastructure, as well as your insights on implementing the \neffective solutions to these challenges. Today's hearing is \nfocused on a topic that is of critical importance, and the \nChairman has covered much of this, to the health and well being \nof our communities, our environment, and our economy: Clean and \nefficient drinking water and wastewater systems.\n    All Americans deserve this. We deserve to have reliable, \naffordable water and sanitation. I am very proud of the \nbipartisan work of this Committee that we accomplished in the \nlast Congress to address America's drinking water and \nwastewater investment backlog. It is such a backlog. The DWWIA \nAct, as we call it, was written by this Committee and is a key \npillar of the Infrastructure Investment and Jobs Act. It \ncreated new programs, opportunities, and support to address \ncurrent water infrastructure needs and ongoing challenges in \nsmall, rural, and disadvantaged communities.\n    In this hearing, we will explore the current state of our \nnation's water resources, the challenges that we face in \nprotecting them, and how we can implement policies in the IIJA \nto help ensure that every person has access to clean drinking \nwater. I look forward to hearing from our expert witnesses and \nengaging in a thoughtful and productive discussion on this \ncrucial issue.\n    The IIJA authorized $55 billion in funding, as the Chairman \nsaid, the largest investment ever, for a range of water \ninfrastructure programs, including grants for small and \ndisadvantaged communities, funding for lead service line \nreplacement, and support for innovative water technologies, as \nwell as funding for wastewater treatment and stormwater \nmanagement. These funding opportunities provide new resources \nto address the current challenges facing our waters \ninfrastructure.\n    Many communities, certainly in our States, are grappling \nwith aging infrastructure that is in need of repair or \nreplacement, while others are dealing with emerging \ncontaminants like PFAS that require specialized treatment \ntechnologies. At the same time, small, rural, and disadvantaged \ncommunities often lack the resources and technical expertise \nneeded to address these challenges, leaving us very vulnerable \nto water quality problems and public health risks.\n    IIJA programs offer a wide range of funding opportunities \nto help address these challenges, from grants and low interest \nloans to technical assistance. These funds can support critical \ninfrastructure upgrades including the replacement of lead \nservice lines, the construction of new treatment facilities--I \nhave actually toured some of these, as I think you have--and \nthe implementation of advanced treatment technologies.\n    Additionally, the funding can support capacity building \ninitiatives, including work force development. Every water \nsystem I go to is really down on the numbers of people who are \ninterested in working in water, but also the retirements that \nwe are seeing across the board in the work force is really \nputting a strain on our systems. So we need to help there. We \nneed to help communities build the expertise needed to manage \nand maintain their water systems, and frankly, we need to get \nthe next generation excited about this as an opportunity and a \ncareer of the future.\n    Despite these significant funding challenges, ongoing unmet \nneeds in small, rural, and disadvantaged communities still \nremain a concern. As they have said, they lack some of the \ntechnical expertise. As we work to implement these programs, it \nwill be important to ensure that the resources are targeted to \nthe communities that need them the most and the necessary \ntechnical assistance and training programs to support them.\n    As the EPA begins to deploy these significant financial \ninvestments in our infrastructure, I have concerns about how \nthe agency is planning to implement some of the directives from \nCongress. We were very explicit in our bills, I think. The \nBiden administration has prioritized its environmental justice \nagenda. But it has not been shy to pull in, I think, political \nfactors as they are doing that that are unrelated to water \nquality and health, key conditions for how this money should be \nspent, and even funding for States as it is reviewed by the \nagency. I am concerned that projects will not be considered \nbased solely on needs related to the explicit statutory \ndirectives of safeguarding human health, keeping rates \naffordable, and protecting the environment.\n    While all of us support empowering communities through \neconomic development, it is important that we recognize that \nFederal investments to the Safe Drinking Water Act and Clean \nWater Act, as amended by the IIJA, should be directed to \nprojects where the needs are most acute and in line with what \nCongress directed the agency to do in the statute. We shouldn't \nbe sidetracked from responsibly investing in our aging \ninfrastructure because we have such a historic bipartisan \nsuccess here.\n    Water systems do not align neatly with the Administration's \neffort to use census tracts to define EJ communities or \npoliticizing the distribution of funds. We have run into this \nin West Virginia in some of the definitions. Congress was \nclear: Funding through DWWIA should encourage State flexibility \nthrough funding pots like the SRFs, and other grant programs \nshoul

### FUNCTION TO TOKENIZE

In [48]:
## create function to read a globbed list
# define function
def tokenize_file(file):
    '''
    Takes a single file, reads it and pushes through nlp pipeline into a spacy.doc
    para = a single file
    '''
    with open(file, "r") as text:
        all_text = text.read()
        return nlp(all_text)

In [52]:
## save senate hearing as nlp doc
doc = tokenize_file(hearing[0])
doc

[Senate Hearing 118-22]
[From the U.S. Government Publishing Office]


                                                        S. Hrg. 118-22

                   IMPLEMENTING IIJA: PERSPECTIVES ON
          THE DRINKING WATER AND WASTEWATER INFRASTRUCTURE ACT

=======================================================================

                                HEARING

                               BEFORE THE

                              COMMITTEE ON
                      ENVIRONMENT AND PUBLIC WORKS

                          UNITED STATES SENATE

                    ONE HUNDRED EIGHTEENTH CONGRESS

                             FIRST SESSION

                               __________

                             MARCH 15, 2023

                               __________

  Printed for the use of the Committee on Environment and Public Works

[GRAPHIC NOT AVAILABLE IN TIFF FORMAT]


        Available via the World Wide Web: http://www.govinfo.gov

                               __________


                    U.S. GOVERNMENT PUBLISHING OFFICE
52-512 PDF                  WASHINGTON : 2023

-----------------------------------------------------------------------------------



               COMMITTEE ON ENVIRONMENT AND PUBLIC WORKS

                    ONE HUNDRED EIGHTEENTH CONGRESS

                             FIRST SESSION

                  THOMAS R. CARPER, Delaware, Chairman
          SHELLEY MOORE CAPITO, West Virginia, Ranking Member

BENJAMIN L. CARDIN, Maryland         KEVIN CRAMER, North Dakota
BERNARD SANDERS, Vermont             CYNTHIA M. LUMMIS, Wyoming
SHELDON WHITEHOUSE, Rhode Island     MARKWAYNE MULLIN, Oklahoma
JEFF MERKLEY, Oregon                 PETE RICKETTS, Nebraska
EDWARD J. MARKEY, Massachusetts      JOHN BOOZMAN, Arkansas
DEBBIE STABENOW, Michigan            ROGER WICKER, Mississippi
MARK KELLY, Arizona                  DAN SULLIVAN, Alaska
ALEX PADILLA, California             LINDSEY O. GRAHAM, South Carolina
JOHN FETTERMAN, Pennsylvania

               Courtney Taylor, Democratic Staff Director
               Adam Tomlinson, Republican Staff Director


                            C O N T E N T S

                              ----------
                                                                   Page

                             MARCH 15, 2023
                           OPENING STATEMENTS

Carper, Hon. Thomas R., U.S. Senator from the State of Delaware..     1
Capito, Hon. Shelley Moore, U.S. Senator from the State of West
  Virginia.......................................................     3

                               WITNESSES

Fox, Hon. Radhika, Assistant Administrator, Office of Water,
  Environmental Protection Agency................................     6
    Prepared statement...........................................     9
    Responses to additional questions from Senator Carper........    18
    Response to an additional question from Senator Fetterman....    23
    Responses to additional questions from Senator Capito........    25
    Response to an additional question from:
        Senator Cramer...........................................    28
        Senator Lummis...........................................    30
    Responses to additional questions from:
        Senator Mullin...........................................    30
        Senator Sullivan.........................................    32
Hayman, Randy E., Commissioner and CEO, Philadelphia Water
  Department.....................................................    70
    Prepared statement...........................................    73
    Responses to additional questions from Senator Carper........    82
Sigmund, Thomas W., President, National Association of Clean
  Water Agencies, Executive Director, NEW Water..................    90
    Prepared statement...........................................    93
    Responses to additional questions from Senator Carper........   161
Emery, Katheryn D., Director, Division of Water and Waste
  Management, West Virginia Department of Environmental
  Protection.....................................................   166
    Prepared statement...........................................   168
    Responses to additional questions from Senator Carper........   175

                          ADDITIONAL MATERIAL

Letter to Senator Charles Schumer et al. from the American
  Sustainable Business Network, March 6, 2023....................    45
Letter to Senators Carper and Capito from the California
  Association of Sanitation Agencies, March 15, 2023.............   188
Letter to Senators Carper and Capito from American Rivers, March
  14, 2023.......................................................   192
Testimony of the Council of Infrastructure Financing Authorities,
  March 15, 2023.................................................   220


 IMPLEMENTING IIJA: PERSPECTIVES ON THE DRINKING WATER AND WASTEWATER
                           INFRASTRUCTURE ACT

                              ----------


                       WEDNESDAY, MARCH 15, 2023

                                       U.S. Senate,
                 Committee on Environment and Public Works,
                                                    Washington, DC.
    The Committee met, pursuant to notice, at 10:05 a.m. in
room 406, Dirksen Senate Office Building, Hon. Thomas R. Carper
(Chairman of the Committee) presiding.
    Present: Senators Carper, Capito, Cardin, Markey, Kelly,
Cramer, Lummis, Sullivan, and Ricketts.

          OPENING STATEMENT OF HON. THOMAS R. CARPER,
            U.S. SENATOR FROM THE STATE OF DELAWARE

    Senator Carper. Good morning. Let me call this hearing to
order.
    We are here today to examine the implementation of the
Drinking Water and Wastewater portions of the Bipartisan
Infrastructure Law. As you will recall, this historic
bipartisan law is helping to deliver clean drinking water to
millions of households and schools across our country.
    Before we do that, let me start by saying how grateful I am
to both panels of witnesses that are joining us today,
including representatives of drinking water, clean water, as
well as small and large utilities. We are particularly
appreciative that Assistant Administrator Radhika Fox, who
leads EPA's Office of Water, has joined us.
    Welcome.
    To all of our guests; we have a lot of folks, Senator
Capito, I don't think we have had that many photos before a
hearing in a long time. We want to remember this day.
    Yesterday, the Biden administration took a major step in
addressing the presence of toxic forever chemicals known as
PFAS in our drinking water. This announcement was some 20 years
in the making. It is an issue that is very important to, as it
turns out, to West Virginia and to Delaware, and frankly, to
all the other 48 States across the country. I want to commend
the President; I want to commend Administrator Regan, Assistant
Administrator Fox, and all of EPA for proposing a thoughtful,
science based, national drinking water standard for PFAS.
    This critical step to protecting our drinking water comes
on top of the President calling for significant investments to
protect our public health and environment in his proposed 2024
budget released last week. In his budget, the President
requested more than $12 billion for EPA, $1.9 billion, a 19
percent increase from the 2023 enacted level. More than $4
billion of that proposal is reserved for water infrastructure.
That includes an additional $219 million for grants to reduce
the amount of lead in drinking water, to test for and remove
lead in schools, and to replace lead pipes.
    This budget builds on the Committee's work in the
Bipartisan Infrastructure Law to invest in our nation's water
infrastructure, which brings us to the topic of today's
hearing: Oversight of the implementation of the drinking water
and wastewater portions of the Bipartisan Infrastructure Law.
    As we have discussed, Democrats and Republicans on this
panel, it is not just enough to enact landmark legislation like
this, but it is important that it be appropriately implemented
and that we exercise our responsibilities with respect to
oversight. That is part of what we are doing here today.
    Our work on this Committee to improve our water
infrastructure is personal to me. We have some folks here from
West Virginia who have joined us; welcome.
    If you're from West Virginia, raise your hand. If you would
like to be from West Virginia, raise your hand.
    [Laughter.]
    Senator Carper. Almost everybody, for the record.
    Our work in this Committee is to improve our water and
infrastructure. As I said, it is personal to me, rooted in my
faith and my family's history in Raleigh County, West Virginia.
Some of you may recall that Matthew 25 calls on all of us to
actually care for those that are in need, the least of these,
to give those that are thirsty something to drink. For me, this
includes that ensuring that Americans have access to clean,
safe, and reliable water services.
    Some of you may recall, I was born in Beckley, in a coal
mining town in the southern part of the State. For 2 of those 6
years that we actually lived there, my first 6 years of my
life, we lived alongside a stream. Our Ranking Member has heard
of Beaver; she's been to Beaver right outside of Beckley many
times. There is a creek that goes through there called Beaver
Creek. My sister and I lived alongside Beaver Creek.
    We would play along the banks of that creek. We would try
to catch small fish, sometimes frogs, and we were never allowed
to eat any of them. Nor were we allowed to drink the water from
Beaver Creek. That is because many of the nearby septic tanks
were not well maintained, and as a result raw sewage and other
pollution could seep into that creek. At the time, our
situation was not too different from that of many other small
communities in West Virginia and across the country.
    In the years that followed, our Government has responded to
this water crisis by creating grant and later loan programs
that made it easier for communities across our country to build
and upgrade drinking water and wastewater treatment systems.
Over time, these programs languished and were in dire need of
updating.
    That is why I, along with our Ranking Member, Senator
Capito, Senator Cardin, Senator Lummis, Senator Duckworth,
Senator Cramer, and many other members of this Committee and
off this Committee joined forces to address this need. We
worked in an overwhelmingly bipartisan way to draft the
Drinking Water and Wastewater Infrastructure Act. You will
recall that our legislation included historic investments in
EPA's State Revolving Funds. Those funds were the primary
vehicle for State and local governments to finance water
infrastructure projects throughout America.
    We advanced our legislation out of Committee unanimously
and later passed it out of the full Senate by a vote of 89 to
2. If the American people are looking for bipartisanship, they
need look no further than this Committee and its work on
infrastructure. This water bill, combined with our Committee's
historic highway legislation, roads, highways, bridges, served
as the foundation of the Bipartisan Infrastructure Law, which
President Biden signed into law in November 2021, a happy day
for all of us.
    The Bipartisan Infrastructure Law invested an unprecedented
$55 billion, $55 billion, that's billion with a B, to improve
drinking water and wastewater systems in communities across our
country, and it was paid for, fully offset. This remains the
single largest water infrastructure investment in our nation's
history. Let me repeat that: This remains the single largest
water infrastructure investment in our nation's history. Now,
EPA has the responsibility of putting these dollars, these
investments, to work for all of the American people.
    Today's hearing is an opportunity to gain a deeper
understanding of how this process is going. This hearing will
allow us to explore future opportunities to improve the way we
invest in our drinking water and wastewater infrastructure.
That includes investigating how the Bipartisan Infrastructure
Law programs are benefiting communities with the greatest need
and what additional authorities or changes might be needed to
make the program function better.
    I like to say, everything I do, I know I can do better. And
as proud as we are of this legislation, we know that we can
still improve on it further. For example, is there more that
could be done to adapt these programs to changes in our climate
and our population and the age of our infrastructure?
    As I said earlier, we look forward to hearing from our
distinguished panels of witnesses today. Before we do, let me
turn to Senator Capito for her opening remarks.
    Senator Capito, you are recognized.

        OPENING STATEMENT OF HON. SHELLEY MOORE CAPITO,
          U.S. SENATOR FROM THE STATE OF WEST VIRGINIA

    Senator Capito. Thank you, Mr. Chairman, and thank all of
you for being here today.
    I would like to thank Assistant Administrator Fox for not
just being here today but for the lines of communication that
you have kept open, as you promised in your hearing when you
came before this Committee. You have stayed true to your word.
I certainly appreciate that, from my perspective.
    I would also like to thank you for finally, after many
years of me banging the gavel and the gong and also with the
Chair to set that safe drinking level for PFAS. That is going
to have many impacts across the country. Certainly, safe,
clean, and healthy water is at the top of the list for all of
us.
    This Committee values your perspectives on the challenges,
and other witnesses' as well, facing this nation's water
infrastructure, as well as your insights on implementing the
effective solutions to these challenges. Today's hearing is
focused on a topic that is of critical importance, and the
Chairman has covered much of this, to the health and well being
of our communities, our environment, and our economy: Clean and
efficient drinking water and wastewater systems.
    All Americans deserve this. We deserve to have reliable,
affordable water and sanitation. I am very proud of the
bipartisan work of this Committee that we accomplished in the
last Congress to address America's drinking water and
wastewater investment backlog. It is such a backlog. The DWWIA
Act, as we call it, was written by this Committee and is a key
pillar of the Infrastructure Investment and Jobs Act. It
created new programs, opportunities, and support to address
current water infrastructure needs and ongoing challenges in
small, rural, and disadvantaged communities.
    In this hearing, we will explore the current state of our
nation's water resources, the challenges that we face in
protecting them, and how we can implement policies in the IIJA
to help ensure that every person has access to clean drinking
water. I look forward to hearing from our expert witnesses and
engaging in a thoughtful and productive discussion on this
crucial issue.
    The IIJA authorized $55 billion in funding, as the Chairman
said, the largest investment ever, for a range of water
infrastructure programs, including grants for small and
disadvantaged communities, funding for lead service line
replacement, and support for innovative water technologies, as
well as funding for wastewater treatment and stormwater
management. These funding opportunities provide new resources
to address the current challenges facing our waters
infrastructure.
    Many communities, certainly in our States, are grappling
with aging infrastructure that is in need of repair or
replacement, while others are dealing with emerging
contaminants like PFAS that require specialized treatment
technologies. At the same time, small, rural, and disadvantaged
communities often lack the resources and technical expertise
needed to address these challenges, leaving us very vulnerable
to water quality problems and public health risks.
    IIJA programs offer a wide range of funding opportunities
to help address these challenges, from grants and low interest
loans to technical assistance. These funds can support critical
infrastructure upgrades including the replacement of lead
service lines, the construction of new treatment facilities--I
have actually toured some of these, as I think you have--and
the implementation of advanced treatment technologies.
    Additionally, the funding can support capacity building
initiatives, including work force development. Every water
system I go to is really down on the numbers of people who are
interested in working in water, but also the retirements that
we are seeing across the board in the work force is really
putting a strain on our systems. So we need to help there. We
need to help communities build the expertise needed to manage
and maintain their water systems, and frankly, we need to get
the next generation excited about this as an opportunity and a
career of the future.
    Despite these significant funding challenges, ongoing unmet
needs in small, rural, and disadvantaged communities still
remain a concern. As they have said, they lack some of the
technical expertise. As we work to implement these programs, it
will be important to ensure that the resources are targeted to
the communities that need them the most and the necessary
technical assistance and training programs to support them.
    As the EPA begins to deploy these significant financial
investments in our infrastructure, I have concerns about how
the agency is planning to implement some of the directives from
Congress. We were very explicit in our bills, I think. The
Biden administration has prioritized its environmental justice
agenda. But it has not been shy to pull in, I think, political
factors as they are doing that that are unrelated to water
quality and health, key conditions for how this money should be
spent, and even funding for States as it is reviewed by the
agency. I am concerned that projects will not be considered
based solely on needs related to the explicit statutory
directives of safeguarding human health, keeping rates
affordable, and protecting the environment.
    While all of us support empowering communities through
economic development, it is important that we recognize that
Federal investments to the Safe Drinking Water Act and Clean
Water Act, as amended by the IIJA, should be directed to
projects where the needs are most acute and in line with what
Congress directed the agency to do in the statute. We shouldn't
be sidetracked from responsibly investing in our aging
infrastructure because we have such a historic bipartisan
success here.
    Water systems do not align neatly with the Administration's
effort to use census tracts to define EJ communities or
politicizing the distribution of funds. We have run into this
in West Virginia in some of the definitions. Congress was
clear: Funding through DWWIA should encourage State flexibility
through funding pots like the SRFs, and other grant programs
should prioritize the need.
    Funds were firewalled between systems of various sizes to
make sure that rural communities, small towns, and big cities
all got their fair share without taking too big a slice of the
pie. The EPA should implement these programs pursuant to the
congressional intent, which resulted from some hard fought
bipartisan compromises.
    I am committed to working on these issues that are so
important to me, the citizens of West Virginia, and our
country.
    I will close by saying what everyone in attendance knows:
Water infrastructure investments are critical to public health,
environmental health, and economic development. I want to see
these new investments create a better quality of life, create
more jobs, and drive the kind of quality of shared health
benefits that we all care about.

### Named Entity Recognition (NER)

#### Spacy easily returns the words that matter to us like names of companies, people, places, art works, numbers, etc.

- ```.ents``` ------------> Finds all entities in doc spacy object.

- ```ent.text``` ------------> The actual text.

- ```ent.label``` ------------> A numeric code for the entity.

- ```ent.label_``` ------------> The word's entity category.

- ```spacy.explain(ent.label_)``` ---------> A description of the category.

In [ ]:
for word in doc.ents[:10]:
    print(word.text, word.label_, spacy.explain(word.label_))
    print("*******")

## Specialized function to capture entity types

In [64]:
## create function to return list of dictionaries of entities and entity labels
## function to find entities
## def function
def cat_entities(doc):
    '''
    Provide tokenized spacy object (doc)
    returns a df with all the entities
    '''
    ent_list = []
    if doc.ents:   #if it has entities within it, I want you to do the following
        for word in doc.ents:
            temp_dict = {"word": word.text,
                         "label": word.label_,
                         "meaning": spacy.explain(word.label_)
                        }
            ent_list.append(temp_dict)

    else:
        print("There are no entities in this text")

    return pd.DataFrame(ent_list)

In [68]:
## test it to find orgs
df = cat_entities(doc)
df

,word,label,meaning
0,Senate,ORG,"Companies, agencies, institutions, etc."
1,the U.S. Government Publishing Office,ORG,"Companies, agencies, institutions, etc."
2,ONE,CARDINAL,Numerals that do not fall under another type
3,"MARCH 15, 2023",DATE,Absolute or relative dates or periods
4,the Committee on Environment and Public Works,ORG,"Companies, agencies, institutions, etc."
...,...,...,...
1499,Eagles,ORG,"Companies, agencies, institutions, etc."
1500,the years,DATE,Absolute or relative dates or periods
1501,Green,GPE,"Countries, cities, states"
1502,Bay,GPE,"Countries, cities, states"
1503,12:27 p.m.,TIME,Times smaller than a day

In [74]:
## search for people only - sometimes it's easier to export this to a csv to scroll up ad down and see what the whole thing looks like.
df.query("label == 'PERSON'").sample(20)

                word   label                      meaning
77            Carper  PERSON  People, including fictional
70            Cramer  PERSON  People, including fictional
751         Sullivan  PERSON  People, including fictional
1190  Katheryn Emery  PERSON  People, including fictional
1263           Emery  PERSON  People, including fictional
216           Capito  PERSON  People, including fictional
1303        Ricketts  PERSON  People, including fictional
649            Obama  PERSON  People, including fictional
845              Fox  PERSON  People, including fictional
1394          Markey  PERSON  People, including fictional
1349          Hayman  PERSON  People, including fictional
734         Ricketts  PERSON  People, including fictional
408           Capito  PERSON  People, including fictional
710           Carper  PERSON  People, including fictional
185           Cardin  PERSON  People, including fictional
1183           Emery  PERSON  People, including fictional
1292          Hayman  PERSON  People, including fictional
253      Kathy Emery  PERSON  People, including fictional
279           Capito  PERSON  People, including fictional
1221           Emery  PERSON  People, including fictional

In [72]:
## search for orgs only
df.query("label == 'ORG'")

,word,label,meaning
0,Senate,ORG,"Companies, agencies, institutions, etc."
1,the U.S. Government Publishing Office,ORG,"Companies, agencies, institutions, etc."
4,the Committee on Environment and Public Works,ORG,"Companies, agencies, institutions, etc."
62,"Office of Water, \n Environmental Protection ...",ORG,"Companies, agencies, institutions, etc."
76,Philadelphia Water \n,ORG,"Companies, agencies, institutions, etc."
...,...,...,...
1466,Committee,ORG,"Companies, agencies, institutions, etc."
1467,the Federal Government,ORG,"Companies, agencies, institutions, etc."
1469,Federal,ORG,"Companies, agencies, institutions, etc."
1498,Packers,ORG,"Companies, agencies, institutions, etc."
1499,Eagles,ORG,"Companies, agencies, institutions, etc."

In [78]:
## CALL SAMPLE 30
df["label"].unique()

array(['ORG', 'CARDINAL', 'DATE', 'PERSON', 'GPE', 'NORP', 'LAW', 'TIME',
       'FAC', 'MONEY', 'PERCENT', 'LOC', 'ORDINAL', 'QUANTITY', 'PRODUCT',
       'EVENT'], dtype=object)